config/routes.rb
Website::Application.routes.draw do
  root to: 'static_pages#home'

  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/mango',   to: 'static_pages#mango'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
      <small>
        by Amanda McWhorter
      </small>
      <nav>
        <!--<ul>-->
          <!--<li><%= link_to "About Me", about_path %></li>-->
          <!--<li><%= link_to "Contact Me", contact_path %></li>-->
        <!--</ul>-->
      </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <a class="navbar-brand" href="/">Amanda's Avenue</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About Me", about_path %></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Amanda's Avenue</title>
      <%= stylesheet_link_tag    "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
    </head>
    <body>
        <%= render 'layouts/header' %>
        <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="jumbotron">
          <div class="container">
            <!--<h1>Welcome to Amanda's Avenue</h1>-->
            <!--<p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>-->
            <!--<p><a class="btn btn-primary btn-lg" role="button">Learn more &raquo;</a></p>-->
          </div>
        </div>
        <!--<div class="widewrapper main">-->
          <!--<img src="../images/cover_photo_mnts.JPG" class="img-responsive" alt="JOHN C. LOWERY, INC">-->
        <!--</div>-->
        <div class="container">
          <%= yield %>
        </div>
        <%= render 'layouts/footer' %>
    </body>
</html>

app/views/static_pages/about.html.erb
<!DOCTYPE html>
<html>
    <head>
      <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
      <title>Amanda's Avenue</title>
    </head>
    <body>
        <h1>About Me</h1>
        <ul class="nav nav-tabs">
          <li class="active"><a data-toggle="tab" href="#intro">Intro</a></li>
          <li><a data-toggle="tab" href="#funfacts">Fun Facts</a></li>
          <li><a data-toggle="tab" href="#resume">Resume</a></li>
        </ul>
        <div class="well">
          <div class="tab-content">
            <div id="intro" class="tab-pane fade in active">
              <div class="row">
                <div class="col-lg-6">
                  <%= image_tag "about_me.JPG" %>
                </div>
                <div class="col-lg-6">
                  <p>I grew up in a small town in Southern California. I moved to San Francisco in 2011 to pursue my degree in
                    computer science at San Francisco State University. Here I am, two years later. I am preparing to
                    graduate in just two months. I am excited to start my career as a Software Engineer and can not wait
                    to see where life takes me.
                  </p>
                </div>
              </div>
            </div>
            <div id="funfacts" class="tab-pane fade">
              <h3>Favorite Activities</h3>
              <ul>
                <li>Volleyball - indoor and outdoor</li>
                <li>Baking</li>
                <li>Reading</li>
                <li>Playing with my cat Mango</li>
              </ul>
              <h3>Hobbies</h3>
              <ul>
                <li>Baking</li>
                <li>Crafts (sewing, knitting, scrapbooking)</li>
                <li>Programming</li>
              </ul>
            </div>
            <div id="resume" class="tab-pane fade">
              <h3>Amanda McWhorter</h3>
              <h4>Education</h4>
              <li>San Francisco State University</li>
              <li>Graduation date: May 2014</li>
              <li>Major: Computer Science</li>
              <h4>Work Experience</h4>
              <li>Manilla - Web Development and QA Intern</li>
              <li>SFSU Communications Dept. - Student Web Assistant</li>
              <li>Epsilon Systems Inc. - Data Entry</li>
              <h4>Qualification and Other Experience</h4>
              <li>Languages: C, C++, Java, Ruby, PHP, JavaScript, HTML, CSS</li>
              <li>frameworks: Ruby on Rails, BootStrap</li>
              <li>Databases: MySQL, Postresql, SQL</li>
              <li>Version Control: git, svn</li>
              <li>Operating Systems: Linux, MacOX, Windows</li>
              <li>Other: Unix, UML, Microsoft Office, Microsoft Project, SAP ERP</li>
            </div>
          </div>
        </div>
    </body>
</html>

app/views/static_pages/contact.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Amanda's Avenue</title>
    </head>
    <body>
        <h1>Contact Me</h1>
        <p>
          This is the contact page
        </p>
    </body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Amanda's Avenue</title>

      <link href="../bootstrap/css/bootstrap.css" rel="stylesheet">
      <link href="../bootstrap/css/bootstrap-responsive.css" rel="stylesheet">

      <script>
          // Load this when the DOM is ready
          $(function(){
              // You used .myCarousel here.
              // That's the class selector not the id selector,
              // which is #myCarousel
              $('#myCarousel').carousel();
          });
      </script>
    </head>
    <body>
        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">Cottonwood Lakes Trip 2013</h2>
            <p class="lead">Last summer me and some friends did an overnight backpacking trip to Cottonwood Lakes,
              located in the southern Sierra's.</p>
            <button type="button" class="btn btn-primary btn-sm">View details</button>
            <%= link_to "static_pages#mango", mango_path, class: "btn btn-primary btn-sm" %>
          </div>
          <div class="col-md-5">
            <%= image_tag 'me_cwl.JPG', :class => "featurette-image img-responsive", :alt => "cottonwood lakes photo" %>
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-5">
            <%= image_tag 'mango.JPG', :class => "featurette-image img-responsive", :alt => "mango the orange cat" %>
          </div>
          <div class="col-md-7">
            <h2 class="featurette-heading">Mango the Orange Cat</h2>
            <p class="lead">We adopted Mango from the SFSPCA in April of 2013.</p>
            <button type="button" class="btn btn-primary btn-sm">View details</button>
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">Upcoming Events</h2>
            <p class="lead">Graduating from San Francisco State University in May 2014 with a Bachelor's of Science in Computer Science.</p>
          </div>
          <div class="col-md-5">
            <%= image_tag 'SFState_Logo_V_rgb_2in.png', :class => "featurette-image img-responsive", :alt => "san francisco state logo" %>
          </div>
        </div>

        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->
    </body>
</html>

app/views/static_pages/mango.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Amanda's Avenue - Mango</title>

      <link href="../bootstrap/css/bootstrap.css" rel="stylesheet">
      <link href="../bootstrap/css/bootstrap-responsive.css" rel="stylesheet">

    </head>
    <body>
    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">Mango the Orange Cat <span class="text-muted">It'll blow your mind.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-md-5">
        <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
      </div>
    </div>
    </body>
</html>